networks:
  terraform:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 1

services:
  terraform:
    image: sinfallas/terraform-all-in-one:latest
    hostname: terraform
    container_name: terraform
    pull_policy: always
    restart: always
    ports:
      - 3000:3000
    environment:
      - AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXX
      - AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXX
      - AWS_DEFAULT_REGION=XXXXXXXXXXXX
      - TF_VAR_aws_region=XXXXXXXXXXXX
      - TF_VAR_aws_vpc=vpc-XXXXXXXXXXXX
      - TF_VAR_aws_subnet=subnet-XXXXXXX
      - TF_VAR_rnombre=example
      - TF_VAR_url=https://example.com
      - TF_VAR_rtag=example
      - TF_VAR_rtoken=XXXXXXXXXXXXXXXXXXXXXX
      - TF_VAR_ubuntupass=example
      - TF_VAR_gitlabpass=example
      - TF_VAR_nombreinstancia=example
      - TF_VAR_nombregruposeguridad=example
    volumes:
#      - ./config.json:/etc/semaphore/config.json
      - ./semaphore_data:/app
      - ./recursos:/recursos
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - terraform
